### ISSUE TITLE
Folder structure disappears when closing a second webbrowser window

### ISSUE THREAD

**Issue by cedricalfonsi** [passbolt/passbolt_browser_extension#105]
## ISSUE NAME
* Passbolt Version: 2.14.0
* Platform and Target: Windows 10, Edge, Firefox or Chrome browser
-- Operating system: Ubuntu
-- PHP: Newest
-- Web server: Don't know.. Used installation script for Passbolt for ubuntu
-- Database server:  Don't know.. Used installation script for Passbolt for ubuntu

### What you did
1. You have previously open another window of the browser; 
2. You are closing this new window; 
3. You come back to passbolt. 

### What happened
Folderstructure is gone. After a refresh of the page the folder structure is back.

### What you expected to happen
Folderstructure should still be there. Not only after a refresh of the page.

Thank you @davoezzz for the report.

**Comment by stripthis** [comment]
This issue is solved with v2.13.7 published today.

**Comment by davoezzz** [comment]
@stripthis We are already running V2.14.0 and in that version is the problem still running. Also there wasn't any new version published in the last days. How is the status? :)

**Comment by stripthis** [comment]
As far as I know it's fixed (i tested it). You need to make sure you have the latest browser extension version installed (v2.13.7)

**Comment by davoezzz** [comment]
@stripthis Excuse me! I was waiting for an update of the passbolt instance itself and not for the Browser extension. Indeed it is fixed with the new version of the browser extension. Thanks!
