### ISSUE TITLE
Not a valid passphrase on Chrome Quickaccess login if certificate not previously accepted

### ISSUE THREAD

**Issue by Athanagorn** [passbolt/passbolt_browser_extension#64]
## ISSUE NAME
* Passbolt Version: Version 2.7.1 of the server, version 2.8.2 of the plugin
* Platform and Target:
-- Browser: Chrome 
-- Server: Self-Hosted on Debian

### What you did
Try to login with the right passphrase in the new Quickaccess inputbox

### What happened
Got message "this is not a valid passphrase" while the password is valid.
![2019-04-09 14_10_04-Nouvel onglet](https://user-images.githubusercontent.com/20598877/55799945-d5510700-5ad2-11e9-9864-0d0049bce989.png)

### What you expected to happen
I expect the plugin to accept the passphrase, or at least to be more explicit in the error message.
The problem seems to be linked to the self signed certificate used for the passbolt server. You first need to go to the passbolt page, accept the security warnings from Chrome, then you will be able to use the plugin. The error message is misleading with some people trying to enter multiple times the good password and getting an error message about it being invalid.

**Comment by cedricalfonsi** [comment]
Hello @Athanagorn,

Thank your for the report.
We'll investigate it and we will keep you posted.

**Comment by cedricalfonsi** [comment]
Fixed with v2.8.3

**Comment by dmarc007** [comment]
I am Still Facing this issue with multiple users. 

using AWS self hosted EC2 server. 

Using software version : 4.9.1-1 (Aug 14, 2024) AMI ID : ami-003cab8e6a27e2950

**Comment by stripthis** [comment]
@dmarc007 are you sure this is the same issue, this issue is very old (~5 years). Can you open a new thread with the information details?

**Comment by dmarc007** [comment]
I have opened new thread as you asked for. Please help me there!!

Not a valid passphrase when passphrase is correct #228
